# SPDX-FileCopyrightText: 2023 MASH project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `email` variable needs to be provided to this playbook, via --extra-vars"
  when: "email is not defined or email == '<email>'"

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `password` variable needs to be provided to this playbook, via --extra-vars"
  when: "password is not defined or password == '<password>'"

- name: Ensure Mobilizon service is started
  ansible.builtin.service:
    name: "{{ mobilizon_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the Mobilizon instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: Create user account
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} exec {{ mobilizon_identifier }}  mobilizon_ctl users.new {{ email | quote }} --password {{ password | quote }}"
  register: mobilizon_create_account_result
  failed_when:
    - mobilizon_create_account_result.rc > 0
