# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023, 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Mobilizon installation tasks
  when: mobilizon_enabled | bool
  tags:
    - setup-all
    - setup-mobilizon
    - install-all
    - install-mobilizon
  block:
    - name: Validate Mobilizon configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Mobilizon
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform tasks to add users automatically to Mobilizon
  when: mobilizon_enabled | bool
  tags:
    - ensure-mobilizon-users-created
    - ensure-users-created
  block:
    - name: Add users to Mobilizon automatically
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_users_auto.yml"

- name: Perform tasks to add users manually to Mobilizon
  when: mobilizon_enabled | bool
  tags:
    - create-user-mobilizon
    - create-admin-mobilizon
  block:
    - name: Add users to Mobilizon manually
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_user_manual.yml"

- name: Perform Mobilizon uninstallation tasks
  when: not mobilizon_enabled | bool
  tags:
    - setup-all
    - setup-mobilizon
  block:
    - name: Uninstall Mobilizon
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
