# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Mobilizon systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mobilizon_identifier }}.service"
  register: mobilizon_service_stat

- name: Uninstall Mobilizon systemd services and files
  when: mobilizon_service_stat.stat.exists | bool
  block:
    - name: Ensure Mobilizon systemd service is stopped
      ansible.builtin.service:
        name: "{{ mobilizon_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Mobilizon systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mobilizon_identifier }}.service"
        state: absent

    - name: Ensure Mobilizon support files do not exist
      ansible.builtin.file:
        path: "{{ mobilizon_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Mobilizon local config path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ mobilizon_config_path }}"
      register: mobilizon_config_path_deletion_result
      changed_when: mobilizon_config_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Mobilizon local tzdata path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ mobilizon_tzdata_path }}"
      register: mobilizon_tzdata_path_deletion_result
      changed_when: mobilizon_tzdata_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Mobilizon local uploads path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ mobilizon_uploads_path }}"
      register: mobilizon_uploads_path_deletion_result
      changed_when: mobilizon_uploads_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Mobilizon local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ mobilizon_data_path }}"
      register: mobilizon_data_path_deletion_result
      changed_when: mobilizon_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Mobilizon base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ mobilizon_base_path }}"
      register: mobilizon_base_path_deletion_result
      changed_when: mobilizon_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Mobilizon container network does not exist
      when: mobilizon_container_network_deletion_enabled
      block:
        - name: Ensure Mobilizon container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ mobilizon_container_network }}"
            state: absent
          register: mobilizon_network_deletion_result

        - name: Ensure Mobilizon container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ mobilizon_container_network }}
          register: mobilizon_network_deletion_result
          changed_when: mobilizon_container_network in mobilizon_network_deletion_result.stdout

- name: Check existence of Mobilizon local data path
  ansible.builtin.stat:
    path: "{{ mobilizon_data_path }}"
  register: mobilizon_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Mobilizon local data path
  when: mobilizon_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Mobilizon instance has been removed, some old data remains in `" + mobilizon_data_path + "`. Feel free to delete it."
        ]
      }}
