# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required mobilizon settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - mobilizon_identifier
    - mobilizon_uid
    - mobilizon_gid
    - mobilizon_hostname
    - mobilizon_container_network
    - mobilizon_database_username
    - mobilizon_database_password
    - mobilizon_database_hostname
    - mobilizon_secret_key_base
    - mobilizon_secret_key

- name: Run if Traefik is enabled
  when: mobilizon_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required mobilizon Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - mobilizon_container_labels_traefik_hostname
