# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "mobilizon_container_port", "new": "mobilizon_container_http_port" }
    - { "old": "mobilizon_http_header_content_permission_policy", "new": "mobilizon_http_header_permissions_policy" }

- name: Fail if required Mobilizon settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - mobilizon_identifier
    - mobilizon_uid
    - mobilizon_gid
    - mobilizon_hostname
    - mobilizon_container_network
    - mobilizon_database_password
    - mobilizon_database_hostname
    - mobilizon_secret_key_base
    - mobilizon_secret_key

- name: Run if Traefik is enabled
  when: mobilizon_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Mobilizon are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - mobilizon_container_labels_traefik_hostname
